##################################################periodictable################################################
print("######################################################################################################")
print("#                                                                                                    #")
print("#                                                                                                    #")
print("#          This program is made for genrating structure after scaning the any bond                   #")
print("#                                                                                                    #")
print("#                                                                                                    #")
print("######################################################################################################")
atomic_symbols = {
    1: 'H', 2: 'He', 3: 'Li', 4: 'Be', 5: 'B', 6: 'C', 7: 'N', 8: 'O', 9: 'F', 10: 'Ne',
    11: 'Na', 12: 'Mg', 13: 'Al', 14: 'Si', 15: 'P', 16: 'S', 17: 'Cl', 18: 'Ar', 19: 'K', 20: 'Ca',
    21: 'Sc', 22: 'Ti', 23: 'V', 24: 'Cr', 25: 'Mn', 26: 'Fe', 27: 'Co', 28: 'Ni', 29: 'Cu', 30: 'Zn',
    31: 'Ga', 32: 'Ge', 33: 'As', 34: 'Se', 35: 'Br', 36: 'Kr', 37: 'Rb', 38: 'Sr', 39: 'Y', 40: 'Zr',
    41: 'Nb', 42: 'Mo', 43: 'Tc', 44: 'Ru', 45: 'Rh', 46: 'Pd', 47: 'Ag', 48: 'Cd', 49: 'In', 50: 'Sn',
    51: 'Sb', 52: 'Te', 53: 'I', 54: 'Xe', 55: 'Cs', 56: 'Ba', 57: 'La', 58: 'Ce', 59: 'Pr', 60: 'Nd',
    61: 'Pm', 62: 'Sm', 63: 'Eu', 64: 'Gd', 65: 'Tb', 66: 'Dy', 67: 'Ho', 68: 'Er', 69: 'Tm', 70: 'Yb',
    71: 'Lu', 72: 'Hf', 73: 'Ta', 74: 'W', 75: 'Re', 76: 'Os', 77: 'Ir', 78: 'Pt', 79: 'Au', 80: 'Hg',
    81: 'Tl', 82: 'Pb', 83: 'Bi', 90: 'Th', 91: 'Pa', 92: 'U', 93: 'Np', 94: 'Pu', 95: 'Am', 96: 'Cm',
    97: 'Bk', 98: 'Cf', 99: 'Es', 100: 'Fm', 101: 'Md', 102: 'No', 103: 'Lr', 104: 'Rf', 105: 'Db', 106: 'Sg',
    107: 'Bh', 108: 'Hs', 109: 'Mt', 110: 'Ds', 111: 'Rg', 112: 'Cn', 113: 'Nh', 114: 'Fl', 115: 'Mc', 116: 'Lv',
    117: 'Ts', 118: 'Og'
}

#####################################################end#########################################################

###################################### mofication list fn########################################################
def modify_data(data_list):
    modified_data = []
    for line in data_list:
        values = line.split()
        if len(values) == 6:
            atomic_number = int(values[1])  # Get the atomic number
            atomic_symbol = atomic_symbols.get(atomic_number, "Unknown")
            x, y, z = map(float, values[3:6])
            modified_data.append(f"{atomic_symbol} {x} {y} {z}")
    return modified_data

################################# .com file fn ##################################################################
def create_gaussian_com_file(file_path, data_list,conectivity,processor,memory,info):
    with open(file_path, 'w') as com_file:
        # Write the Gaussian job type and other settings (modify as needed)
        com_file.write(memory)
        com_file.write(processor)
        com_file.write(info)
        com_file.write("Gaussian input generated by Python\n\n")

        # Write the molecule section with atomic symbols and coordinates
        com_file.write("0 1\n")  # Charge and multiplicity (modify as needed)
        for line in data_list:
            symbol, x, y, z = line.split()
            x = '{:.6f}'.format(float(x))  # Format x-coordinate with 6 decimal places
            y = '{:.6f}'.format(float(y))  # Format y-coordinate with 6 decimal places
            z = '{:.6f}'.format(float(z))  # Format z-coordinate with 6 decimal places
            atom_line = f"{symbol:>2}{'':7}{x:>12}{y:>12}{z:>12}"  # Proper spacing and zero-padding
            com_file.write(atom_line + "\n")
            
        com_file.write("\n")
        for line in conectivity:
            com_file.write(line)
            
#######################################################end########################################################



###################################################### main boby #################################################
#print("\nThis program is made for genrating structure after scaning the any bond ")
print("\n")
file_name = str(input("Enter your scan .log file name : "))
print("\n")
number_of_atom = int(input("Enter total number of atom in your molecule : "))
print("\n")
opt_freq = str(input("Enter your opt+freq.com name : "))
print("\n")
memory = str(input("Specify the memory : "))
print("\n")
processor = str(input("Specify the processor : "))
print("\n")
basisset = str(input("Enter basis set (ex- 6-311++g(d,p) ): "))
print("\n")
method  = str(input("Enter method (ex- b3lyp ): "))
print("\n")
states = str(input("Enter no. of states you chosen : "))
print("\n")
file = open(file_name)
data = file.readlines()
###########################################extracting coordinates from scan file ##################################
text = []

for i in data:
    m = i.replace(" " ,"")
    text.append(m)

c=[]
for i in range(0,len(text)):
    if text[i] == "--Stationarypointfound.\n" :
        c.append(i)
        
#print(c,len(c))
m=[]
#k=0
for i in c:
    for j in range(i,0,-1):
        if "Rotationalconstants" in text[j]:
            m.append(j)
            break

alldata=[]

n_o_a=number_of_atom+1
for i in m:
    hdata=[]
    for j in range(i-n_o_a,i-1):
        hdata.append(data[j])
    
    alldata.append(hdata)
##########################################all cordinates are extracted in alldata list##############################
structure = 1
con = open(opt_freq)
conectivity = con.readlines()
conectivity = conectivity[9+number_of_atom:len(conectivity)]

memory="%mem="+memory+"GB\n"
processor = "%nproc="+processor+"\n"
info = "# td=(singlets,nstates="+states+") "+method+"/"+basisset+" geom=connectivity\n\n"

for i in alldata:
    
    modified_list = modify_data(i)

    output_file_path = str(structure)+".com"
    
    create_gaussian_com_file(output_file_path, modified_list,conectivity,memory,processor,info)
    
    structure=structure+1


######################################runing all file script#########################################################
f = open('all_run.sh','w')

for i in range(1,structure+1):
    f.write('tsp g16 '+str(i)+'.com &\n')

f.close()

print("\nplease look 2-3 gentrated .com for confirmation")
print("\nfor to genrate .log file run this command >> bash all_run.sh\n ")
print("note: before running please do top.")    
#print("\ncredits: VSR group")


        
